In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

Dataset http://tinyurl.com/data-preprocess

In [2]:
dataset = pd.read_csv("data.csv")
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [3]:
dataset.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

We need to remove Nan values so doing that

In [4]:
dataset.isnull().any()

Country      False
Age           True
Salary        True
Purchased    False
dtype: bool

In [5]:
dataset.isnull().any

<bound method DataFrame.any of    Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False>

We can delete the data or find its mean to replace Nan 

In [6]:
dataset['Age'].fillna((dataset['Age'].mean()),inplace=True)
dataset['Salary'].fillna((dataset['Salary'].mean()),inplace=True)

In [7]:
dataset

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [8]:
dataset['Country'].value_counts()

France     4
Spain      3
Germany    3
Name: Country, dtype: int64

In [9]:
dataset['Purchased'].value_counts()

Yes    5
No     5
Name: Purchased, dtype: int64

In [10]:
dataset.isnull().any()

Country      False
Age          False
Salary       False
Purchased    False
dtype: bool

Now seperate independent and dependent variables

In [11]:
x= dataset.iloc[:,0:3].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [12]:
y = dataset.iloc[:,3:4].values
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [13]:
x.shape

(10, 3)

Categorical text Encoding

In [14]:
import sklearn

In [15]:
sklearn.__version__

'0.22.1'

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [17]:
ct = ColumnTransformer([
        ("on",        # Just a name
         OneHotEncoder(), # The transformer class
         [0]            # The column(s) to be applied on.
         )
    ], remainder='passthrough'
)
x = ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [18]:
x.shape

(10, 5)

Removing the dummy Data 

In [19]:
x=x[:,1:]

In [20]:
x.shape

(10, 4)

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
lb = LabelEncoder()
y = lb.fit_transform(y)

C:\Users\dharmendra\Anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [23]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [24]:
y.shape

(10,)

In [25]:
x

array([[0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x=sc.fit_transform(x)
x

array([[-6.54653671e-01, -6.54653671e-01,  7.58874362e-01,
         7.49473254e-01],
       [-6.54653671e-01,  1.52752523e+00, -1.71150388e+00,
        -1.43817841e+00],
       [ 1.52752523e+00, -6.54653671e-01, -1.27555478e+00,
        -8.91265492e-01],
       [-6.54653671e-01,  1.52752523e+00, -1.13023841e-01,
        -2.53200424e-01],
       [ 1.52752523e+00, -6.54653671e-01,  1.77608893e-01,
         6.63219199e-16],
       [-6.54653671e-01, -6.54653671e-01, -5.48972942e-01,
        -5.26656882e-01],
       [-6.54653671e-01,  1.52752523e+00,  0.00000000e+00,
        -1.07356980e+00],
       [-6.54653671e-01, -6.54653671e-01,  1.34013983e+00,
         1.38753832e+00],
       [ 1.52752523e+00, -6.54653671e-01,  1.63077256e+00,
         1.75214693e+00],
       [-6.54653671e-01, -6.54653671e-01, -2.58340208e-01,
         2.93712492e-01]])

Train Test split

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [29]:
x_train.shape

(8, 4)

In [30]:
x_test.shape

(2, 4)

In [31]:
y_train.shape

(8,)

In [32]:
y_test.shape

(2,)